// SPDX-License-Identifier: Apache-2.0
import { ActionButton, PrimaryButton } from '../primitives'
import type { UseSetupFlowReturn } from '../useSetupFlow'

export function TutorialPromptStep({ flow }: { flow: UseSetupFlowReturn }) {
  return (
    <div style={{ maxWidth: '640px', margin: '2rem auto', padding: '0 1rem' }}>
      <h1 ref={flow.stepHeadingRef} tabIndex={-1} style={{ outline: 'none' }}>First Words tutorial</h1>

      <div role="note" aria-label="scripted tutorial disclaimer" style={{ background: 'rgba(251,191,36,0.08)', border: '1px solid rgba(251,191,36,0.35)', borderRadius: '6px', padding: '1rem 1.25rem', marginTop: '1rem' }}>
        <p style={{ margin: 0, fontWeight: 600, color: '#fbbf24', fontSize: '0.875rem' }}>Scripted tutorial — not AI-generated</p>
        <p style={{ margin: '0.5rem 0 0', fontSize: '0.825rem', color: '#fde68a' }}>
          Alex Chen's responses are pre-authored, not generated by a language model.
          The tutorial teaches how the app works — once your model finishes
          downloading you'll switch to real AI-powered conversations automatically.
        </p>
      </div>

      <div style={{ marginTop: '1rem' }}>
        <p style={{ fontSize: '0.875rem', color: '#d4d4d8', marginBottom: '0.5rem', fontWeight: 500 }}>What you'll learn in 3–5 minutes:</p>
        <ul style={{ margin: 0, paddingLeft: '1.25rem', fontSize: '0.875rem', color: '#a1a1aa', lineHeight: 1.7 }}>
          <li>How state meters track conversation dynamics turn by turn</li>
          <li>How scenario events fire at threshold crossings and change NPC behaviour</li>
          <li>The three ways a session can end: success, failure, or timeout</li>
          <li>What each rubric dimension measures and how the debrief scores you</li>
        </ul>
      </div>

      <div style={{ display: 'flex', gap: '0.5rem', marginTop: '1.5rem' }}>
        <PrimaryButton disabled={flow.actionLoading} onClick={() => void flow.handleStartTutorial()}>
          {flow.actionLoading ? 'Starting…' : 'Start the tutorial'}
        </PrimaryButton>
        <ActionButton onClick={() => { flow.resetAction(); flow.setStep('installing') }}>Back</ActionButton>
      </div>
    </div>
  )
}
