"""convsim_prompt — Layered prompt composer for Conversation Simulator NPC turns."""

from .composer import LAYER_ORDER, SYSTEM_LAYER_ORDER, compose_turn_prompt
from .debrief_composer import DebriefComposerInput, DebriefTurnRecord, compose_debrief_prompt
from .debrief_output import (
    DEBRIEF_NARRATIVE_SCHEMA,
    DEBRIEF_SYSTEM_PREAMBLE,
    DebriefNarrative,
    DebriefValidationError,
    TurningPoint,
    parse_debrief_narrative,
)
from .flyting_judge import (
    AttackSurfaceTrait,
    DEFAULT_HOOK_BONUS,
    DEFAULT_JUDGE_ANCHORS,
    DEFAULT_JUDGE_WEIGHTS,
    DEFAULT_THEME_DECAY,
    DroppedHook,
    EvidenceClaim,
    FLYTING_JUDGE_OUTPUT_SCHEMA,
    HookClaim,
    JUDGE_DEVICES,
    JUDGE_DIMENSIONS,
    JUDGE_FOULS,
    JUDGE_LAYER_ORDER,
    JUDGE_THEMES,
    JudgeAnchor,
    JudgeEvent,
    JudgeRubric,
    MAX_VERIFIED_HOOKS,
    VolleyJudgeInput,
    VolleyJudgment,
    compose_volley_judge_prompt,
    parse_volley_judgment,
)
from .inspection import PromptInspector
from .layers import UNTRUSTED_CONTENT_BEGIN, UNTRUSTED_CONTENT_END
from .output_validator import (
    OutputValidationResult,
    OutputViolation,
    validate_npc_output,
)
from .turn_output import (
    extract_json_object,
    RubricObservation,
    RuntimeProtocol,
    SAFE_FALLBACK_UTTERANCE,
    SAFE_REDIRECT_UTTERANCE,
    SAFE_STOP_UTTERANCE,
    SafetyStatus,
    SessionControl,
    TurnEvent,
    TurnOutput,
    ValidationError,
    parse_turn_output,
)
from .types import (
    DifficultySettings,
    NPC_TURN_OUTPUT_SCHEMA,
    NpcData,
    NpcPrivatePersona,
    NpcPublicPersona,
    PromptBundle,
    PromptComposerInput,
    ResponseStyleOverrides,
    SafetyPolicy,
    ScenarioData,
    SessionState,
    TranscriptEntry,
)

__all__ = [
    "compose_turn_prompt",
    "LAYER_ORDER",
    "SYSTEM_LAYER_ORDER",
    "UNTRUSTED_CONTENT_BEGIN",
    "UNTRUSTED_CONTENT_END",
    "PromptInspector",
    "DifficultySettings",
    "NPC_TURN_OUTPUT_SCHEMA",
    "NpcData",
    "NpcPrivatePersona",
    "NpcPublicPersona",
    "PromptBundle",
    "PromptComposerInput",
    "ResponseStyleOverrides",
    "SafetyPolicy",
    "ScenarioData",
    "SessionState",
    "TranscriptEntry",
    # Turn output parser
    "parse_turn_output",
    "TurnOutput",
    "TurnEvent",
    "RubricObservation",
    "SafetyStatus",
    "SessionControl",
    "ValidationError",
    "RuntimeProtocol",
    "extract_json_object",
    # Flyting judge (per-volley scoring, Stage 3)
    "compose_volley_judge_prompt",
    "parse_volley_judgment",
    "FLYTING_JUDGE_OUTPUT_SCHEMA",
    "JUDGE_DIMENSIONS",
    "JUDGE_THEMES",
    "JUDGE_DEVICES",
    "JUDGE_FOULS",
    "JUDGE_LAYER_ORDER",
    "MAX_VERIFIED_HOOKS",
    "DEFAULT_JUDGE_WEIGHTS",
    "DEFAULT_JUDGE_ANCHORS",
    "DEFAULT_HOOK_BONUS",
    "DEFAULT_THEME_DECAY",
    "AttackSurfaceTrait",
    "JudgeAnchor",
    "JudgeEvent",
    "JudgeRubric",
    "VolleyJudgeInput",
    "VolleyJudgment",
    "HookClaim",
    "DroppedHook",
    "EvidenceClaim",
    "SAFE_FALLBACK_UTTERANCE",
    "SAFE_REDIRECT_UTTERANCE",
    "SAFE_STOP_UTTERANCE",
    # Output content validator
    "validate_npc_output",
    "OutputValidationResult",
    "OutputViolation",
    # Debrief prompt composer and output parser
    "compose_debrief_prompt",
    "DebriefComposerInput",
    "DebriefTurnRecord",
    "DEBRIEF_NARRATIVE_SCHEMA",
    "DEBRIEF_SYSTEM_PREAMBLE",
    "DebriefNarrative",
    "DebriefValidationError",
    "TurningPoint",
    "parse_debrief_narrative",
]
