#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Nightly real-model smoke test (issue #457).

Exercises the whole play pipeline against a **real local model** — no fake
runtime anywhere — and fails with a *classified* verdict so a red nightly is
triageable from the job summary alone.

What a full run does
--------------------
1. **download** — fetch the smallest registry model (role ``starter``:
   Qwen3 4B Instruct Q4_K_M) unless the CI cache already holds it.
2. **checksum** — hash the on-disk file and compare it to the registry
   ``sha256``.  This runs on cache hits too, so a drifted or truncated cached
   file fails loudly instead of silently feeding a corrupt model to the smoke.
3. **runtime** — start llama-cpp-python's OpenAI-compatible server on the GGUF
   and start ``convsim-core`` wired to it (``CONVSIM_RUNTIME_ID=llama_cpp``).
4. **conversation** — create and start a session on the built-in
   ``behavioral_interview`` scenario (the NPC opening is authored scenario text,
   not a generation), then submit a scripted multi-turn player conversation.
   Every NPC *reply* is generated by the real model under the turn-output JSON
   schema.
5. **debrief** — end the session and generate the debrief, asserting a *scored*
   debrief comes back (non-empty rubric dimensions, numeric overall score,
   non-empty summary).
6. **budget** — compare measured latencies against the documented budgets
   scaled by ``--ci-hardware-factor``.

``convsim-core``'s turn endpoint is synchronous — it returns the completed NPC
turn in a single response rather than streaming ``npc.token`` events (token
streaming is added by the ``apps/api`` gateway, which is not exercised here).
The smoke therefore measures full end-to-end turn latency (which subsumes
time-to-first-token) against the ``full_response_ms`` budget.

Failure classification
----------------------
Every failure is attributed to one class, printed in a banner, written to the
JSON report (``failure_class``) and the GitHub step summary, and mapped to a
distinct exit code:

===========  ====  =======================================================
class        exit  meaning
===========  ====  =======================================================
``budget``      1  latency regression: the pipeline worked, just too slowly
``download``    2  model could not be fetched (network / HTTP / missing cache)
``checksum``    3  SHA-256 drift: on-disk bytes ≠ registry ``sha256``
``runtime``     4  llama-server or convsim-core crashed, hung, or 5xx'd
``pipeline``    5  servers healthy but an end-to-end assertion failed
``timeout``     6  wall-clock budget exhausted (phase named in the message)
===========  ====  =======================================================

Transcript content is fully scripted (see ``SCRIPTED_PLAYER_TURNS``) and holds
no user data, so short NPC excerpts are logged and reported — they are the
evidence that a real model, not a canned fallback, drove the conversation.
``save_transcript`` is false, so no transcript file is written.

Usage
-----
Resolve the starter model from the registry (writes ``$GITHUB_OUTPUT``)::

    python scripts/nightly-model-smoke.py --print-registry-model starter

Download only (cache miss)::

    python scripts/nightly-model-smoke.py --download-only \\
        --model-id <id> --model-url <url> --model-sha256 <hex>

Verify an already-cached file without running the smoke::

    python scripts/nightly-model-smoke.py --verify-only \\
        --model-id <id> --model-sha256 <hex>

Full smoke::

    python scripts/nightly-model-smoke.py \\
        --model-id qwen3-4b-instruct-q4_k_m \\
        --model-sha256 <hex> \\
        --ci-hardware-factor 20 \\
        --wall-clock-budget-s 1200 \\
        --report-path /tmp/smoke-report.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import statistics
import subprocess
import sys
import tempfile
import threading
import time
import urllib.error
import urllib.request
from collections import deque
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

REPO_ROOT = Path(__file__).parent.parent
REGISTRY_PATH = REPO_ROOT / "model-registry" / "registry.yaml"

# Documented latency budgets (ms) from docs/performance.md and the
# LATENCY_BUDGETS constant in packages/shared/src/types/metrics.ts.
# Keep in sync manually; the script intentionally does not import TS source.
#
# Only full_response_ms is budget-checked here:
#   - TTFT needs token streaming (the apps/api gateway), which this smoke does
#     not stand up, and full_response_ms subsumes it;
#   - session_start_ms and debrief_ms are measured and reported but NOT checked.
#     The NPC opening is authored scenario text, not a generation, so session
#     start is not inference-bound and the CI hardware factor does not apply to
#     it; debrief generation has no documented budget (docs/performance.md).
BUDGETS_MS = {
    "full_response_ms": 10_000,
}

# Regression tolerance: measured may exceed the CI budget by at most this factor.
REGRESSION_TOLERANCE = 1.20

MODELS_DIR = Path.home() / ".convsim" / "models" / "llm"

# Ports for the two local processes started during a smoke run.
LLAMA_SERVER_PORT = 7356  # convsim-core's default CONVSIM_LLAMA_CPP_BASE_URL port
CORE_PORT = 7399

# Wall-clock budget for the whole run, in seconds.  The script — which knows
# which phase it is in — must fail first with an attributed verdict instead of
# GitHub killing the job with an unattributable "The operation was canceled",
# so this has to clear the job's timeout-minutes *minus the steps that run
# before the script does*: checkout, pip install, cache restore and (on a cache
# miss) the 2.5 GB download, together up to ~8 min of the 30 min job.  20 min
# therefore leaves the script's own deadline the first one to trip.
# See docs/real-model-smoke.md.
DEFAULT_WALL_CLOCK_BUDGET_S = 1200.0  # 20 min

# Scripted player turns — deliberately the same script as the fake-runtime
# playthrough in tests/e2e/test_scripted_playthrough.py, so the real-model
# nightly and the per-PR smoke exercise the same conversation shape.
SCRIPTED_PLAYER_TURNS = (
    "I have five years of experience in software development.",
    "My biggest achievement was building a cross-team API platform.",
    "I believe in clear documentation and knowledge sharing.",
)

SCENARIO_ID = "behavioral_interview"

# Longest NPC excerpt copied into the log / report (scripted content only).
EXCERPT_CHARS = 160

# A debrief summary shorter than this is not a usable coaching summary.
MIN_SUMMARY_CHARS = 20

# How much slower the debrief generation is allowed to be than one NPC turn
# before we stop calling it slow and start calling it hung.  Only used to size
# request timeouts (see run_smoke) — debrief latency itself is not budget-checked.
DEBRIEF_SLOWDOWN_FACTOR = 2.0


# ── Failure classification ────────────────────────────────────────────────────


class FailureClass:
    """Mutually exclusive failure classes, each with its own exit code."""

    BUDGET = "budget"
    DOWNLOAD = "download"
    CHECKSUM = "checksum"
    RUNTIME = "runtime"
    PIPELINE = "pipeline"
    TIMEOUT = "timeout"


EXIT_CODES = {
    FailureClass.BUDGET: 1,
    FailureClass.DOWNLOAD: 2,
    FailureClass.CHECKSUM: 3,
    FailureClass.RUNTIME: 4,
    FailureClass.PIPELINE: 5,
    FailureClass.TIMEOUT: 6,
}

# What a human should do first for each class.  Printed in the failure banner
# and the step summary so triage does not require reading this file.
REMEDIES = {
    FailureClass.BUDGET: (
        "Latency regression, not a broken pipeline. Compare measured_ms in the "
        "report artifact against recent nightlies. If the runner class or the "
        "starter model changed, re-calibrate --ci-hardware-factor; otherwise "
        "look for a prompt-size or sampling-parameter regression."
    ),
    FailureClass.DOWNLOAD: (
        "The model could not be fetched. Check that the registry URL is still "
        "live (scripts/validate-registry.py --url-check) and that Hugging Face "
        "is reachable. Nothing about the app changed — re-run the job."
    ),
    FailureClass.CHECKSUM: (
        "SHA-256 drift: the bytes on disk do not match model-registry/registry.yaml. "
        "Either the pinned upstream file was replaced (re-pin with "
        "scripts/pin-model.py and review the new file) or the cached download is "
        "corrupt. The local copy has been deleted, but the Actions cache entry has "
        "not: delete it too (`gh cache delete <key>`, or bump the cache-key prefix "
        "in model-smoke-nightly.yml) or every re-run restores the same bad bytes. "
        "Do NOT relax this check."
    ),
    FailureClass.RUNTIME: (
        "llama-server or convsim-core crashed, hung, or returned 5xx. The child "
        "stderr tail is printed above the banner. Likely causes: runner OOM on "
        "model load, an incompatible llama-cpp-python wheel, or an unhandled "
        "exception in the turn pipeline."
    ),
    FailureClass.PIPELINE: (
        "Both servers were healthy but an end-to-end assertion failed: the model "
        "ran and produced output the product rejects. Inspect per-turn "
        "used_fallback / native-structured-output flags in the report artifact."
    ),
    FailureClass.TIMEOUT: (
        "The run exhausted its wall-clock budget in the phase named above. "
        "Either inference got much slower or a phase hung. Check phase_durations_s "
        "in the report artifact before raising --wall-clock-budget-s."
    ),
}


class SmokeFailure(Exception):
    """A failure with a known class, so CI can distinguish *why* the smoke failed."""

    def __init__(self, failure_class: str, message: str, *, phase: Optional[str] = None) -> None:
        super().__init__(message)
        self.failure_class = failure_class
        self.phase = phase

    @property
    def exit_code(self) -> int:
        return EXIT_CODES[self.failure_class]

    @property
    def remedy(self) -> str:
        return REMEDIES[self.failure_class]


# ── Wall-clock budget ─────────────────────────────────────────────────────────


class Deadline:
    """Tracks the run's wall-clock budget and which phase is consuming it."""

    def __init__(self, budget_s: float) -> None:
        self.budget_s = budget_s
        self._start = time.monotonic()
        self._phase = "startup"
        self._phase_start = self._start
        self.phase_durations_s: Dict[str, float] = {}

    @property
    def elapsed_s(self) -> float:
        return time.monotonic() - self._start

    @property
    def remaining_s(self) -> float:
        return self.budget_s - self.elapsed_s

    @property
    def phase(self) -> str:
        return self._phase

    def enter(self, phase: str) -> None:
        """Close out the current phase's duration, start a new one, check the budget."""
        self._close_phase(phase)
        self.check()

    def finish(self) -> Dict[str, float]:
        """Close the books without checking the budget.

        Called from ``run_smoke``'s ``finally``, where an exhausted budget has
        already been classified: raising here would escape the handler and throw
        the verdict away, turning a reportable timeout into a bare traceback.
        """
        self._close_phase("done")
        return self.phase_durations_s

    def _close_phase(self, next_phase: str) -> None:
        now = time.monotonic()
        self.phase_durations_s[self._phase] = round(
            self.phase_durations_s.get(self._phase, 0.0) + (now - self._phase_start), 1
        )
        self._phase = next_phase
        self._phase_start = now

    def check(self) -> None:
        if self.remaining_s <= 0:
            raise SmokeFailure(
                FailureClass.TIMEOUT,
                f"Wall-clock budget of {self.budget_s:.0f} s exhausted during phase "
                f"{self._phase!r} (elapsed {self.elapsed_s:.0f} s)",
                phase=self._phase,
            )

    def cap(self, timeout_s: float) -> float:
        """Clamp a request timeout to what is left of the budget."""
        self.check()
        return max(5.0, min(timeout_s, self.remaining_s))


# ── Registry ──────────────────────────────────────────────────────────────────


def resolve_registry_model(role: str, registry_path: Path = REGISTRY_PATH) -> Dict[str, Any]:
    """Return ``{id, url, sha256, size_gb}`` for the registry model with ``role``.

    Single source of truth for the workflow: the cache key, the download and the
    checksum verification all come from this one lookup, so they cannot drift
    apart. ``yaml`` is imported lazily so the module imports without PyYAML.
    """
    import yaml  # lazy: keeps this module importable for unit tests without PyYAML

    registry = yaml.safe_load(registry_path.read_text(encoding="utf-8"))
    matches = [m for m in registry.get("models", []) if m.get("role") == role]
    if not matches:
        raise SmokeFailure(
            FailureClass.DOWNLOAD,
            f"No model with role {role!r} in {registry_path}",
        )
    if len(matches) > 1:
        raise SmokeFailure(
            FailureClass.DOWNLOAD,
            f"Registry has {len(matches)} models with role {role!r}; expected exactly one",
        )
    model = matches[0]
    download = model.get("download", {})
    sha256 = download.get("sha256")
    url = download.get("url")
    if not sha256 or not url:
        raise SmokeFailure(
            FailureClass.DOWNLOAD,
            f"Registry model {model.get('id')!r} is missing download.url or download.sha256",
        )
    return {
        "id": model["id"],
        "url": url,
        "sha256": sha256,
        "size_gb": model.get("size_gb"),
    }


def _emit_github_output(values: Dict[str, Any]) -> None:
    """Write ``key=value`` lines to $GITHUB_OUTPUT (and always to stdout)."""
    lines = [f"{k}={v}" for k, v in values.items()]
    for line in lines:
        print(line)
    out = os.environ.get("GITHUB_OUTPUT")
    if out:
        with open(out, "a", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")


# ── Download and checksum ─────────────────────────────────────────────────────


def _download_with_progress(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    print(f"  Downloading {url[:80]}…")
    req = urllib.request.Request(url, headers={"User-Agent": "convsim-smoke/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=600) as resp, open(dest, "wb") as f:
            total = int(resp.headers.get("Content-Length", 0)) or None
            downloaded = 0
            chunk = 1 << 20  # 1 MB
            while True:
                buf = resp.read(chunk)
                if not buf:
                    break
                f.write(buf)
                downloaded += len(buf)
                if total:
                    pct = int(downloaded / total * 100)
                    print(
                        f"\r  {pct}% ({downloaded // 1_048_576} / {total // 1_048_576} MB)",
                        end="",
                        flush=True,
                    )
        print()
    except OSError as exc:
        # Network failure, HTTP error, or a full disk — all "could not fetch the
        # model", none of which say anything about the app under test.  Remove the
        # partial file so a re-run does not checksum-fail on a truncated download.
        dest.unlink(missing_ok=True)
        raise SmokeFailure(
            FailureClass.DOWNLOAD,
            f"Download failed for {url[:120]}: {exc}",
        ) from exc


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def verify_model_checksum(path: Path, expected: str, *, delete_on_mismatch: bool = True) -> str:
    """Hash ``path`` and compare to ``expected``; raise on drift.

    A mismatch deletes the file by default: leaving a known-bad GGUF in the CI
    cache would make every subsequent run fail on the same corrupt bytes, since
    the cache key is the expected hash and a cache hit skips the download.
    """
    if not path.exists():
        raise SmokeFailure(
            FailureClass.DOWNLOAD,
            f"Model file not found: {path}. The cache restore produced no model and no "
            "download ran — check the cache key and the download step.",
        )
    actual = sha256_file(path)
    if actual != expected:
        size_mb = path.stat().st_size // 1_048_576
        if delete_on_mismatch:
            path.unlink(missing_ok=True)
        raise SmokeFailure(
            FailureClass.CHECKSUM,
            f"SHA-256 drift on {path.name} ({size_mb} MB): registry expects "
            f"{expected}, on-disk bytes hash to {actual}"
            + (". The bad file was deleted." if delete_on_mismatch else ""),
        )
    print(f"  SHA-256 verified: {actual[:16]}… ({path.stat().st_size // 1_048_576} MB)")
    return actual


def download_model(url: str, sha256: str, model_id: str, models_dir: Path = MODELS_DIR) -> Path:
    dest = models_dir / f"{model_id}.gguf"
    if dest.exists():
        print(f"  Model already on disk: {dest}")
    else:
        _download_with_progress(url, dest)
    verify_model_checksum(dest, sha256)
    return dest


# ── Server helpers ────────────────────────────────────────────────────────────


def _start_llama_server(model_path: Path, port: int) -> subprocess.Popen:
    """Start llama-cpp-python's OpenAI-compatible server on the given port.

    convsim-core's ``llama_cpp`` runtime adapter talks to this server over
    ``/v1/chat/completions`` (see services/convsim-core/.../runtime/llama_cpp.py).
    """
    return subprocess.Popen(
        [sys.executable, "-m", "llama_cpp.server",
         "--model", str(model_path),
         "--host", "127.0.0.1", "--port", str(port),
         "--n_ctx", "8192"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def _start_core(data_dir: Path, port: int, llama_port: int, llama_timeout_s: float) -> subprocess.Popen:
    """Start convsim-core wired to the local llama-server via env overrides."""
    env = os.environ.copy()
    env.update({
        # Select the real llama.cpp runtime (default is the deterministic fake).
        "CONVSIM_RUNTIME_ID": "llama_cpp",
        # Point the adapter at the llama-server started above.
        "CONVSIM_LLAMA_CPP_BASE_URL": f"http://127.0.0.1:{llama_port}",
        "CONVSIM_LLAMA_CPP_CONTEXT_LENGTH": "8192",
        # The adapter's per-request timeout must outlast the slowest call we
        # intend to measure (the debrief), or the adapter's 30 s default kills a
        # slow-but-reportable generation first and convsim-core answers 500 — a
        # latency problem misfiled as a RUNTIME crash.  See run_smoke.
        "CONVSIM_LLAMA_CPP_TIMEOUT": str(int(llama_timeout_s)),
        "CONVSIM_DATA_DIR": str(data_dir),
        "CONVSIM_LOG_DIR": str(data_dir / "logs"),
        "CONVSIM_DB_DIR": str(data_dir / "db"),
        "CONVSIM_PACKS_DIR": str(data_dir / "packs"),
        "CONVSIM_PORT": str(port),
        "CONVSIM_HOST": "127.0.0.1",
    })
    return subprocess.Popen(
        [sys.executable, "-m", "uvicorn", "convsim_core.main:app",
         "--host", "127.0.0.1", "--port", str(port), "--log-level", "warning"],
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def _wait_for_http(url: str, timeout_s: float, label: str, proc: Optional[subprocess.Popen] = None) -> None:
    """Poll ``url`` until it answers, or raise a RUNTIME failure.

    When ``proc`` is given, an exited child short-circuits the wait: a crashed
    server is a runtime failure we can name immediately rather than something to
    keep polling for until the timeout.
    """
    deadline = time.monotonic() + timeout_s
    last_err: Optional[Exception] = None
    while time.monotonic() < deadline:
        if proc is not None and proc.poll() is not None:
            raise SmokeFailure(
                FailureClass.RUNTIME,
                f"{label} exited with code {proc.returncode} before becoming ready",
            )
        try:
            with urllib.request.urlopen(url, timeout=5):
                return
        except urllib.error.HTTPError:
            # A response (even 4xx) means the server is up and routing.
            return
        except Exception as exc:  # noqa: BLE001 — connection refused while booting
            last_err = exc
            time.sleep(1)
    raise SmokeFailure(
        FailureClass.RUNTIME,
        f"{label} did not become ready within {timeout_s:.0f} s ({last_err})",
    )


# ── HTTP helpers (every transport-level failure is a RUNTIME failure) ──────────


def _request_json(
    url: str,
    *,
    payload: Optional[dict] = None,
    timeout: float,
    expect: Sequence[int] = (200, 201),
) -> dict:
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"} if data is not None else {},
        method="POST" if data is not None else "GET",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = json.loads(resp.read())
            if resp.status not in expect:
                raise SmokeFailure(
                    FailureClass.PIPELINE,
                    f"{url} returned HTTP {resp.status}, expected one of {list(expect)}",
                )
            return body
    except urllib.error.HTTPError as exc:
        detail = exc.read(2048).decode(errors="replace")
        # 5xx is the server breaking; 4xx is the server rejecting what we asked
        # for, i.e. an end-to-end assertion about the API contract.
        cls = FailureClass.RUNTIME if exc.code >= 500 else FailureClass.PIPELINE
        raise SmokeFailure(cls, f"{url} returned HTTP {exc.code}: {detail[:500]}") from exc
    except SmokeFailure:
        raise
    except Exception as exc:  # noqa: BLE001 — connection reset, timeout, bad JSON
        raise SmokeFailure(
            FailureClass.RUNTIME,
            f"{url} did not answer with usable JSON after {timeout:.0f} s: {exc!r}",
        ) from exc


def _npc_turn_content(events: Sequence[dict]) -> str:
    """Return the NPC utterance from a turn/start response's events, or ''."""
    for ev in events:
        if ev.get("event_type") in ("npc_turn", "npc_opening"):
            return ev.get("payload", {}).get("content", "")
    return ""


def _excerpt(text: str) -> str:
    collapsed = " ".join(text.split())
    return collapsed[:EXCERPT_CHARS] + ("…" if len(collapsed) > EXCERPT_CHARS else "")


# ── Assertions (pure, unit-tested) ────────────────────────────────────────────


def evaluate_turns(turns: List[Dict[str, Any]]) -> tuple[List[str], List[str]]:
    """Check the conversation really came from the model.  Returns (failures, warnings).

    The fallback policy is applied only to turns marked ``model_generated``: the
    NPC opening is authored scenario text, so counting it would make the
    "every turn fell back" check unreachable.

    An empty NPC utterance is always a failure.  A single fallback turn is a
    warning — a 4 B model does occasionally emit output the validator rejects,
    and the product's job is to recover from that — but if *every* generated turn
    fell back to the canned safe utterance then no real NPC turns were produced
    and the smoke proved nothing, so that is a failure.
    """
    failures: List[str] = []
    warnings: List[str] = []
    if not turns:
        return (["No turns were recorded; the conversation never ran"], warnings)

    for turn in turns:
        label = turn.get("label", f"turn {turn.get('turn_number')}")
        if not turn.get("npc_excerpt"):
            failures.append(f"{label}: completed but returned no NPC utterance")

    generated = [t for t in turns if t.get("model_generated")]
    if not generated:
        failures.append("No model-generated NPC turns were recorded")
        return (failures, warnings)

    fallbacks = [t for t in generated if t.get("used_fallback")]
    if len(fallbacks) == len(generated):
        failures.append(
            f"All {len(generated)} model-generated NPC turns fell back to the canned "
            "safe utterance; the real model produced no usable turn output"
        )
    elif fallbacks:
        warnings.append(
            f"{len(fallbacks)} of {len(generated)} model-generated NPC turns fell back "
            "to the safe utterance"
        )
    return (failures, warnings)


def evaluate_debrief(debrief: Optional[Dict[str, Any]]) -> tuple[List[str], List[str]]:
    """Check that a *scored* debrief was produced.  Returns (failures, warnings)."""
    failures: List[str] = []
    warnings: List[str] = []
    if not debrief:
        return (["No debrief was produced"], warnings)

    scores = debrief.get("scores")
    if not isinstance(scores, dict) or not scores:
        failures.append(
            "Debrief has no rubric dimension scores; the model emitted no scorable "
            "rubric_observations across the whole conversation"
        )

    overall = debrief.get("overall_score")
    if not isinstance(overall, (int, float)) or isinstance(overall, bool):
        failures.append(f"Debrief overall_score is not numeric (got {overall!r})")
    elif not 0 <= overall <= 100:
        failures.append(f"Debrief overall_score {overall} is outside [0, 100]")

    summary = debrief.get("summary") or ""
    if len(summary.strip()) < MIN_SUMMARY_CHARS:
        failures.append(
            f"Debrief summary is shorter than {MIN_SUMMARY_CHARS} characters "
            f"({len(summary.strip())} chars)"
        )

    if debrief.get("used_fallback"):
        # The scores are still real (they come from per-turn rubric observations),
        # so this degrades the debrief narrative rather than invalidating the run.
        warnings.append("Debrief narrative used the deterministic fallback, not model prose")
    if not debrief.get("turning_points"):
        warnings.append("Debrief contains no turning points")
    return (failures, warnings)


def evaluate_budgets(
    measured_ms: Dict[str, float],
    ci_hardware_factor: float,
    budgets_ms: Dict[str, int] = BUDGETS_MS,
    tolerance: float = REGRESSION_TOLERANCE,
) -> tuple[List[str], List[str]]:
    """Compare measurements to scaled budgets.  Returns (failures, report_lines)."""
    failures: List[str] = []
    lines: List[str] = []
    for key, budget_ms in budgets_ms.items():
        measured = measured_ms.get(key)
        if measured is None:
            continue
        ci_budget = budget_ms * ci_hardware_factor
        ceiling = ci_budget * tolerance
        status = "PASS" if measured <= ceiling else "FAIL"
        lines.append(
            f"{key}: {measured:.0f} ms "
            f"(CI budget {ci_budget:.0f} ms × {tolerance} = {ceiling:.0f} ms) → {status}"
        )
        if status == "FAIL":
            failures.append(
                f"{key} = {measured:.0f} ms exceeds CI ceiling {ceiling:.0f} ms "
                f"(documented budget {budget_ms} ms × {ci_hardware_factor} × {tolerance})"
            )
    return (failures, lines)


# ── Reporting ─────────────────────────────────────────────────────────────────


def render_step_summary(results: Dict[str, Any]) -> str:
    """Render the GitHub step summary: verdict, class, timings, what to do next."""
    verdict = results.get("verdict", "unknown")
    icon = {"pass": "✅", "fail": "❌"}.get(verdict, "⚠️")
    lines = [
        f"## {icon} Real-model smoke: {verdict.upper()}",
        "",
        f"- **Model:** `{results.get('model_id')}`",
        f"- **Wall clock:** {results.get('wall_clock_s', 0):.0f} s "
        f"(budget {results.get('wall_clock_budget_s', 0):.0f} s)",
    ]
    if verdict == "fail":
        cls = results.get("failure_class", "unknown")
        lines += [
            f"- **Failure class:** `{cls}` (exit {results.get('exit_code')})",
            "",
            "### Failures",
            *[f"- {f}" for f in results.get("failures", [])],
            "",
            "### What to do",
            REMEDIES.get(cls, "No remedy recorded."),
        ]
    measured = results.get("measured_ms") or {}
    if measured:
        lines += ["", "### Measured latency", "", "| Metric | Measured | CI ceiling |", "|---|---|---|"]
        factor = results.get("ci_hardware_factor", 1.0)
        for key, value in measured.items():
            budget = BUDGETS_MS.get(key)
            ceiling = (
                f"{budget * factor * REGRESSION_TOLERANCE:.0f} ms" if budget else "—"
            )
            lines.append(f"| `{key}` | {value:.0f} ms | {ceiling} |")
    phases = results.get("phase_durations_s") or {}
    if phases:
        lines += ["", "### Phase durations", "", "| Phase | Seconds |", "|---|---|"]
        lines += [f"| `{k}` | {v:.0f} |" for k, v in phases.items()]
    if results.get("warnings"):
        lines += ["", "### Warnings", *[f"- {w}" for w in results["warnings"]]]
    return "\n".join(lines) + "\n"


def _write_step_summary(results: Dict[str, Any]) -> None:
    path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not path:
        return
    try:
        with open(path, "a", encoding="utf-8") as f:
            f.write(render_step_summary(results))
    except OSError as exc:  # never let reporting break the verdict
        print(f"[smoke] Could not write step summary: {exc}", file=sys.stderr)


def _print_banner(failure_class: str, failures: Sequence[str]) -> None:
    bar = "━" * 72
    print(f"\n{bar}", file=sys.stderr)
    print(f"[smoke] FAILED — class: {failure_class.upper()} "
          f"(exit {EXIT_CODES[failure_class]})", file=sys.stderr)
    print(bar, file=sys.stderr)
    for f in failures:
        print(f"  ✗ {f}", file=sys.stderr)
    print(f"\n  → {REMEDIES[failure_class]}", file=sys.stderr)
    print(f"{bar}\n", file=sys.stderr)


def _write_report(report_path: Optional[Path], results: Dict[str, Any]) -> None:
    if not report_path:
        return
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(results, indent=2), encoding="utf-8")
    print(f"[smoke] Report written to {report_path}")


# ── Smoke run ─────────────────────────────────────────────────────────────────


def _drain(stream: object, sink: Optional[deque] = None) -> None:
    """Consume a subprocess pipe in the background to avoid a full-buffer deadlock.

    When ``sink`` (a bounded deque) is given, the most recent lines are retained
    so they can be surfaced if the smoke fails.  The child's stderr is otherwise
    discarded, which makes a server-side 500 undiagnosable from the CI logs — the
    client only ever sees ``HTTPError: 500`` with no server traceback.
    """
    try:
        for raw in stream:  # type: ignore[attr-defined]
            if sink is not None:
                line = raw.decode(errors="replace") if isinstance(raw, bytes) else raw
                sink.append(line.rstrip("\n"))
    except Exception:
        pass


def _dump_stderr_tails(tails: Sequence[tuple[str, deque]]) -> None:
    for label, tail in tails:
        if tail:
            print(f"\n[smoke] ── {label} stderr (last {len(tail)} lines) ──", file=sys.stderr)
            for line in tail:
                print(f"  {label[:4]}| {line}", file=sys.stderr)


def _crashed_child(procs: Sequence[tuple[str, Optional[subprocess.Popen]]]) -> Optional[str]:
    """Return a description of the first child that has exited, if any."""
    for label, proc in procs:
        if proc is not None and proc.poll() is not None:
            return f"{label} exited with code {proc.returncode}"
    return None


def _debug_flags_by_turn(base: str, session_id: str, timeout: float) -> Dict[int, Dict[str, Any]]:
    """Fetch per-turn parse flags from the dev debug endpoint, keyed by game turn.

    Best-effort: the debug drawer is a diagnostic, so a failure here must not
    turn a healthy smoke red.
    """
    try:
        debug = _request_json(f"{base}/sessions/{session_id}/debug", timeout=timeout)
    except SmokeFailure as exc:
        print(f"[smoke] Could not read debug flags ({exc}); continuing.")
        return {}
    return {t["turn_number"]: t for t in debug.get("turns", [])}


def run_smoke(
    model_id: str,
    ci_hardware_factor: float,
    report_path: Optional[Path],
    *,
    model_sha256: Optional[str] = None,
    models_dir: Path = MODELS_DIR,
    wall_clock_budget_s: float = DEFAULT_WALL_CLOCK_BUDGET_S,
) -> int:
    """Run the full scripted smoke.  Returns the process exit code."""
    clock = Deadline(wall_clock_budget_s)
    # A call must be allowed to run past the latency we are about to judge it
    # on, or whoever gives up first decides the verdict instead of us: the
    # adapter's own timeout surfaces as HTTP 500 (class `runtime`, "the server
    # crashed") and our POST timeout surfaces as a transport error (also
    # `runtime`), when the truth is a slow model — class `budget`.
    #
    # The debrief, not a turn, is the slowest single generation (one long
    # structured document against one NPC reply), so the adapter ceiling is
    # sized for it: DEBRIEF_SLOWDOWN_FACTOR × the full-response CI ceiling.
    # Our own POST timeout then sits above the adapter's, so when something
    # really does hang it is the adapter that reports it, with a message that
    # names the knob.  The run's wall-clock deadline — not these timeouts — is
    # what bounds the job.
    full_ceiling_s = (
        BUDGETS_MS["full_response_ms"] * ci_hardware_factor * REGRESSION_TOLERANCE
    ) / 1000
    llama_timeout_s = max(300.0, full_ceiling_s * DEBRIEF_SLOWDOWN_FACTOR + 60.0)
    request_timeout_s = llama_timeout_s + 30.0

    results: Dict[str, Any] = {
        "model_id": model_id,
        "scenario_id": SCENARIO_ID,
        "ci_hardware_factor": ci_hardware_factor,
        "budgets_ms": dict(BUDGETS_MS),
        "ci_budgets_ms": {k: v * ci_hardware_factor for k, v in BUDGETS_MS.items()},
        "regression_tolerance": REGRESSION_TOLERANCE,
        "wall_clock_budget_s": wall_clock_budget_s,
        "measured_ms": {},
        "turns": [],
        "debrief": None,
        "verdict": "pending",
        "failure_class": None,
        "exit_code": None,
        "failures": [],
        "warnings": [],
    }

    model_path = models_dir / f"{model_id}.gguf"
    llama_proc: Optional[subprocess.Popen] = None
    core_proc: Optional[subprocess.Popen] = None
    llama_stderr_tail: deque = deque(maxlen=200)
    core_stderr_tail: deque = deque(maxlen=200)

    try:
        # ── checksum ──────────────────────────────────────────────────────────
        clock.enter("checksum")
        if model_sha256:
            print(f"[smoke] Verifying model checksum before use: {model_path}")
            verify_model_checksum(model_path, model_sha256)
        elif not model_path.exists():
            raise SmokeFailure(
                FailureClass.DOWNLOAD,
                f"Model file not found: {model_path}. Run with --download-only first, "
                "or check that the model cache is populated.",
            )
        else:
            results["warnings"].append(
                "No --model-sha256 given: checksum drift was not checked before the run"
            )

        with tempfile.TemporaryDirectory(prefix="convsim-smoke-") as tmp:
            data_dir = Path(tmp)

            # ── runtime ───────────────────────────────────────────────────────
            clock.enter("runtime_start")
            print(f"\n[smoke] Starting llama-server on port {LLAMA_SERVER_PORT} "
                  f"with model: {model_path.name}")
            llama_proc = _start_llama_server(model_path, LLAMA_SERVER_PORT)
            threading.Thread(target=_drain, args=(llama_proc.stderr, llama_stderr_tail), daemon=True).start()
            threading.Thread(target=_drain, args=(llama_proc.stdout,), daemon=True).start()

            print("[smoke] Waiting for llama-server (model load)…")
            _wait_for_http(
                f"http://127.0.0.1:{LLAMA_SERVER_PORT}/v1/models",
                timeout_s=clock.cap(300.0),
                label="llama-server",
                proc=llama_proc,
            )
            print("[smoke] llama-server ready.")

            print(f"[smoke] Starting convsim-core on port {CORE_PORT}…")
            core_proc = _start_core(data_dir, CORE_PORT, LLAMA_SERVER_PORT, llama_timeout_s)
            threading.Thread(target=_drain, args=(core_proc.stderr, core_stderr_tail), daemon=True).start()
            threading.Thread(target=_drain, args=(core_proc.stdout,), daemon=True).start()

            base = f"http://127.0.0.1:{CORE_PORT}/api"
            _wait_for_http(
                f"{base}/health",
                timeout_s=clock.cap(120.0),
                label="convsim-core",
                proc=core_proc,
            )

            # Sanity-check that the real runtime is wired (not the fake default).
            health = _request_json(f"{base}/health", timeout=clock.cap(30.0))
            runtime_id = health.get("llm_runtime", {}).get("runtime_id")
            results["runtime_id"] = runtime_id
            print(f"[smoke] convsim-core ready (runtime_id={runtime_id}).")
            if runtime_id != "llama_cpp":
                raise SmokeFailure(
                    FailureClass.PIPELINE,
                    f"Expected runtime_id 'llama_cpp' but core reports {runtime_id!r}. "
                    "Check CONVSIM_RUNTIME_ID wiring — the smoke must not run on a fake runtime.",
                )

            # ── conversation ──────────────────────────────────────────────────
            clock.enter("conversation")
            session = _request_json(f"{base}/sessions", payload={
                "scenario_id": SCENARIO_ID,
                "difficulty": "standard",
                "player_role_name": "Smoke Tester",
                "language": "en",
                "input_mode": "text-only",
                "tts_enabled": False,
                "show_state_meters": False,
                "save_transcript": False,  # no transcript file written during smoke runs
                "seed": 42,
            }, timeout=clock.cap(30.0))
            session_id = session["session_id"]
            results["session_id"] = session_id
            print(f"[smoke] Session {session_id} created. Starting session…")

            # /start replays the scenario's authored opening line — no model
            # call — so it is measured for the documented session-start metric but
            # needs no inference-sized timeout.
            t0 = time.monotonic()
            start = _request_json(
                f"{base}/sessions/{session_id}/start",
                payload={},
                timeout=clock.cap(60.0),
            )
            session_start_ms = (time.monotonic() - t0) * 1000
            opening = _npc_turn_content(start.get("events", []))
            print(f"[smoke] NPC opening (authored) in {session_start_ms:.0f} ms: "
                  f"{_excerpt(opening)!r}")
            results["measured_ms"]["session_start_ms"] = round(session_start_ms)
            results["turns"].append({
                "label": "npc_opening",
                "turn_number": 0,
                "model_generated": False,
                "latency_ms": round(session_start_ms),
                "npc_excerpt": _excerpt(opening),
            })

            turn_latencies: List[float] = []
            ended_by_scenario = False
            for i, player_text in enumerate(SCRIPTED_PLAYER_TURNS, start=1):
                clock.check()
                print(f"[smoke] Player turn {i}/{len(SCRIPTED_PLAYER_TURNS)}…")
                t0 = time.monotonic()
                turn = _request_json(
                    f"{base}/sessions/{session_id}/turn",
                    payload={"content": player_text},
                    timeout=clock.cap(request_timeout_s),
                )
                latency_ms = (time.monotonic() - t0) * 1000
                turn_latencies.append(latency_ms)
                npc_text = _npc_turn_content(turn.get("events", []))
                print(f"  {latency_ms:.0f} ms | NPC: {_excerpt(npc_text)!r}")
                results["turns"].append({
                    "label": f"player_turn_{i}",
                    "turn_number": i,
                    "model_generated": True,
                    "latency_ms": round(latency_ms),
                    "npc_excerpt": _excerpt(npc_text),
                    "ending_type": turn.get("ending_type"),
                })
                if turn.get("ending_type"):
                    # The turn pipeline already moved the session to 'Ended', so
                    # POST /end would 409 — see end_session() in the sessions
                    # router.  Record that and skip the explicit end below.
                    ended_by_scenario = True
                    print(f"[smoke] Scenario ended early (ending_type={turn['ending_type']}); "
                          "stopping the scripted turns.")
                    break

            # The median is the headline full-response figure: a single unlucky
            # turn (runner steal, a long NPC answer) must not flap the nightly,
            # while a real regression moves every turn and so moves the median.
            results["measured_ms"]["full_response_ms"] = round(statistics.median(turn_latencies))
            results["measured_ms"]["full_response_max_ms"] = round(max(turn_latencies))

            # Per-turn parse flags tell us whether the model's structured output
            # was accepted or quietly replaced by the safe fallback.
            flags = _debug_flags_by_turn(base, session_id, clock.cap(30.0))
            for turn in results["turns"]:
                flag = flags.get(turn["turn_number"])
                if flag:
                    turn["used_fallback"] = bool(flag.get("used_fallback"))
                    turn["used_native_structured_output"] = bool(
                        flag.get("used_native_structured_output")
                    )

            # ── debrief ───────────────────────────────────────────────────────
            clock.enter("debrief")
            if ended_by_scenario:
                print("[smoke] Session already Ended by the scenario; skipping /end.")
            else:
                print("[smoke] Ending session…")
                _request_json(
                    f"{base}/sessions/{session_id}/end", payload={}, timeout=clock.cap(30.0)
                )
            print("[smoke] Generating debrief (real model call)…")
            t0 = time.monotonic()
            debrief = _request_json(
                f"{base}/sessions/{session_id}/debrief",
                payload={},
                timeout=clock.cap(request_timeout_s),
            )
            debrief_ms = (time.monotonic() - t0) * 1000
            results["measured_ms"]["debrief_ms"] = round(debrief_ms)
            results["debrief"] = {
                "outcome": debrief.get("outcome"),
                "total_turns": debrief.get("total_turns"),
                "scores": debrief.get("scores"),
                "overall_score": debrief.get("overall_score"),
                "summary_excerpt": _excerpt(debrief.get("summary") or ""),
                "strength_count": len(debrief.get("strengths") or []),
                "improvement_count": len(debrief.get("improvements") or []),
                "turning_point_count": len(debrief.get("turning_points") or []),
                "used_fallback": bool(debrief.get("used_fallback")),
                "latency_ms": round(debrief_ms),
            }
            print(f"[smoke] Debrief in {debrief_ms:.0f} ms | "
                  f"overall_score={debrief.get('overall_score')} "
                  f"scores={debrief.get('scores')}")

            # ── assertions ────────────────────────────────────────────────────
            clock.enter("assertions")
            turn_failures, turn_warnings = evaluate_turns(results["turns"])
            debrief_failures, debrief_warnings = evaluate_debrief(debrief)
            results["warnings"] += turn_warnings + debrief_warnings
            pipeline_failures = turn_failures + debrief_failures
            if pipeline_failures:
                results["failures"] = pipeline_failures
                raise SmokeFailure(
                    FailureClass.PIPELINE,
                    f"{len(pipeline_failures)} end-to-end assertion(s) failed",
                )

            # ── budget ────────────────────────────────────────────────────────
            clock.enter("budget")
            budget_failures, budget_lines = evaluate_budgets(
                results["measured_ms"], ci_hardware_factor
            )
            for line in budget_lines:
                print(f"  {line}")
            if budget_failures:
                results["failures"] = budget_failures
                raise SmokeFailure(
                    FailureClass.BUDGET, f"{len(budget_failures)} latency budget(s) exceeded"
                )

            results["verdict"] = "pass"
            results["exit_code"] = 0

    except SmokeFailure as exc:
        # Precedence, strongest evidence first:
        #   1. A crashed child outranks whatever the client saw — "core exited
        #      with code 1" is the real story, not the connection reset it caused.
        #   2. An exhausted wall clock outranks the transport error it produced:
        #      cap() shrinks each request timeout to the budget that is left, so
        #      the last request before the deadline dies client-side and reports
        #      itself as RUNTIME ("the server never answered"). The honest
        #      verdict is TIMEOUT, which is the class whose remedy says to look
        #      at phase_durations_s.
        crashed = _crashed_child((("llama-server", llama_proc), ("convsim-core", core_proc)))
        out_of_time = not crashed and clock.remaining_s <= 0
        if crashed:
            failure_class = FailureClass.RUNTIME
        elif out_of_time:
            failure_class = FailureClass.TIMEOUT
        else:
            failure_class = exc.failure_class
        results["verdict"] = "fail"
        results["failure_class"] = failure_class
        results["exit_code"] = EXIT_CODES[failure_class]
        results["failed_phase"] = exc.phase or clock.phase
        if not results["failures"]:
            results["failures"] = [str(exc)]
        if crashed:
            results["failures"].insert(0, crashed)
        elif out_of_time and exc.failure_class != FailureClass.TIMEOUT:
            results["failures"].insert(
                0,
                f"Wall-clock budget of {wall_clock_budget_s:.0f} s exhausted during phase "
                f"{results['failed_phase']!r} (elapsed {clock.elapsed_s:.0f} s)",
            )
        _dump_stderr_tails((("convsim-core", core_stderr_tail), ("llama-server", llama_stderr_tail)))
        _print_banner(failure_class, results["failures"])

    # Exception, not BaseException: a Ctrl-C should still stop the children (the
    # finally block below) but must not be dressed up as a product failure.
    except Exception as exc:
        results["verdict"] = "fail"
        results["failure_class"] = FailureClass.PIPELINE
        results["exit_code"] = EXIT_CODES[FailureClass.PIPELINE]
        results["failed_phase"] = clock.phase
        results["failures"] = [
            f"Unexpected error in phase {clock.phase!r}: {exc!r} — this is most likely "
            "a bug in the smoke harness itself, not in the product "
            "(tests/scripts/test_nightly_model_smoke.py covers its logic)"
        ]
        _dump_stderr_tails((("convsim-core", core_stderr_tail), ("llama-server", llama_stderr_tail)))
        _print_banner(FailureClass.PIPELINE, results["failures"])

    finally:
        for proc in (core_proc, llama_proc):
            if proc is None:
                continue
            proc.terminate()
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
        results["phase_durations_s"] = clock.finish()
        results["wall_clock_s"] = round(clock.elapsed_s, 1)

    if results["verdict"] == "pass":
        generated = sum(1 for t in results["turns"] if t.get("model_generated"))
        print(f"\n[smoke] PASSED — real model {model_id} produced "
              f"{generated} NPC turn(s) and a scored debrief "
              f"(overall_score={(results['debrief'] or {}).get('overall_score')}) "
              f"in {results['wall_clock_s']:.0f} s.")
        for warning in results["warnings"]:
            print(f"  ! {warning}")

    _write_report(report_path, results)
    _write_step_summary(results)
    return int(results["exit_code"] or 0)


# ── CLI ───────────────────────────────────────────────────────────────────────


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--print-registry-model", metavar="ROLE", default=None,
                        help="Resolve the registry model with this role (e.g. 'starter'), "
                             "write id/url/sha256 to $GITHUB_OUTPUT, and exit.")
    parser.add_argument("--download-only", action="store_true",
                        help="Download and verify the model file, then exit.")
    parser.add_argument("--verify-only", action="store_true",
                        help="Verify the on-disk model against --model-sha256, then exit.")
    parser.add_argument("--model-url", default=None,
                        help="Download URL (required for --download-only).")
    parser.add_argument("--model-sha256", default=None,
                        help="Expected SHA-256 hex. Required for --download-only/--verify-only; "
                             "on a full run the model is re-verified before use when given.")
    parser.add_argument("--model-id", default=None,
                        help="Registry model ID (e.g. qwen3-4b-instruct-q4_k_m).")
    parser.add_argument("--models-dir", default=None,
                        help=f"Directory holding <model-id>.gguf (default {MODELS_DIR}).")
    parser.add_argument("--ci-hardware-factor", type=float, default=1.0,
                        help="Multiplier applied to documented budgets for CI hardware (default 1.0).")
    parser.add_argument("--wall-clock-budget-s", type=float, default=DEFAULT_WALL_CLOCK_BUDGET_S,
                        help=f"Fail with exit {EXIT_CODES[FailureClass.TIMEOUT]} if the run "
                             f"exceeds this many seconds (default {DEFAULT_WALL_CLOCK_BUDGET_S:.0f}).")
    parser.add_argument("--report-path", default=None, help="Write JSON report to this path.")

    args = parser.parse_args(argv)
    models_dir = Path(args.models_dir) if args.models_dir else MODELS_DIR

    try:
        if args.print_registry_model:
            model = resolve_registry_model(args.print_registry_model)
            _emit_github_output({
                "model_id": model["id"],
                "model_url": model["url"],
                "model_sha256": model["sha256"],
                "model_size_gb": model["size_gb"],
            })
            return 0

        if not args.model_id:
            parser.error("--model-id is required")

        if args.download_only:
            if not args.model_url or not args.model_sha256:
                parser.error("--model-url and --model-sha256 are required with --download-only")
            print(f"[smoke] Downloading model {args.model_id}…")
            download_model(args.model_url, args.model_sha256, args.model_id, models_dir)
            return 0

        if args.verify_only:
            if not args.model_sha256:
                parser.error("--model-sha256 is required with --verify-only")
            print(f"[smoke] Verifying cached model {args.model_id}…")
            verify_model_checksum(models_dir / f"{args.model_id}.gguf", args.model_sha256)
            return 0

    except SmokeFailure as exc:
        _print_banner(exc.failure_class, [str(exc)])
        _write_step_summary({
            "verdict": "fail",
            "model_id": args.model_id,
            "failure_class": exc.failure_class,
            "exit_code": exc.exit_code,
            "failures": [str(exc)],
        })
        return exc.exit_code

    return run_smoke(
        args.model_id,
        args.ci_hardware_factor,
        Path(args.report_path) if args.report_path else None,
        model_sha256=args.model_sha256,
        models_dir=models_dir,
        wall_clock_budget_s=args.wall_clock_budget_s,
    )


if __name__ == "__main__":
    sys.exit(main())
